#!/bin/bash



sudo systemctl stop rsyslog.service
sudo systemctl disable rsyslog.service

sudo systemctl stop syslog.socket
sudo systemctl disable syslog.socket




sudo systemctl enable rsyslog.service
sudo systemctl start rsyslog.service


sudo systemctl enable syslog.socket
sudo systemctl start syslog.socket