#!/bin/bash

#sudo apt-add-repository ppa:adiscon/v8-stable
# sudo apt-add-repository ppa:adiscon/v8-devel

sudo apt-get update

sudo apt-get install -y \
    rsyslog \
    rsyslog-elasticsearch \
    rsyslog-gnutls \
    rsyslog-mmanon \
    rsyslog-mmfields \
    rsyslog-mmjsonparse \
    rsyslog-mmnormalize \
    rsyslog-udpspoof \
    rsyslog-utils